---
- hosts: 192.168.133.135
  sudo: yes
  tasks:
    - name: install apache
      yum: name={{ item }} state=present
      with_items:
       - httpd
       - httpd-devel
    - name : copyconfigurefile
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.destination }}"
        owner: root
        group: root
        mode: 0644
      with_items:
          - {src: "/tmp/httpd.conf",destination: "/etc/httpd/conf/httpd.conf"}
    - name : check apache
      service: name=httpd state=started enabled=yes
