{"status": "ok", "data": [
    {"base-currency": "btc", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "btcusdt"},
    {"base-currency": "bch", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "bchusdt"},
    {"base-currency": "eth", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ethusdt"},
    {"base-currency": "etc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "etcusdt"},
    {"base-currency": "ltc", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ltcusdt"},
    {"base-currency": "eos", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "eosusdt"},
    {"base-currency": "xrp", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "xrpusdt"},
    {"base-currency": "omg", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "omgusdt"},
    {"base-currency": "dash", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "dashusdt"},
    {"base-currency": "zec", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "zecusdt"},
    {"base-currency": "ada", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "adausdt"},
    {"base-currency": "steem", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "steemusdt"},
    {"base-currency": "iota", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "iotausdt"},
    {"base-currency": "ocn", "quote-currency": "usdt", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ocnusdt"},
    {"base-currency": "soc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "socusdt"},
    {"base-currency": "ctxc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ctxcusdt"},
    {"base-currency": "act", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "actusdt"},
    {"base-currency": "btm", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btmusdt"},
    {"base-currency": "bts", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btsusdt"},
    {"base-currency": "ont", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ontusdt"},
    {"base-currency": "iost", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "iostusdt"},
    {"base-currency": "ht", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "htusdt"},
    {"base-currency": "trx", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "trxusdt"},
    {"base-currency": "dta", "quote-currency": "usdt", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "dtausdt"},
    {"base-currency": "neo", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "neousdt"},
    {"base-currency": "qtum", "quote-currency": "usdt", "price-precision": 2, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "qtumusdt"},
    {"base-currency": "smt", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "smtusdt"},
    {"base-currency": "ela", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "elausdt"},
    {"base-currency": "ven", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "venusdt"},
    {"base-currency": "theta", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "thetausdt"},
    {"base-currency": "snt", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "sntusdt"},
    {"base-currency": "zil", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "zilusdt"},
    {"base-currency": "xem", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "xemusdt"},
    {"base-currency": "nas", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "nasusdt"},
    {"base-currency": "ruff", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ruffusdt"},
    {"base-currency": "hc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "hcusdt"},
    {"base-currency": "let", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "letusdt"},
    {"base-currency": "mds", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mdsusdt"},
    {"base-currency": "storj", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "storjusdt"},
    {"base-currency": "elf", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "elfusdt"},
    {"base-currency": "itc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "itcusdt"},
    {"base-currency": "cvc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cvcusdt"},
    {"base-currency": "gnt", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "gntusdt"},
    {"base-currency": "xmr", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "xmrbtc"},
    {"base-currency": "bch", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "bchbtc"},
    {"base-currency": "eth", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ethbtc"},
    {"base-currency": "ltc", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ltcbtc"},
    {"base-currency": "etc", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "etcbtc"},
    {"base-currency": "eos", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "eosbtc"},
    {"base-currency": "omg", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "omgbtc"},
    {"base-currency": "xrp", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "main", "symbol": "xrpbtc"},
    {"base-currency": "dash", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "dashbtc"},
    {"base-currency": "zec", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "zecbtc"},
    {"base-currency": "ada", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "adabtc"},
    {"base-currency": "steem", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "steembtc"},
    {"base-currency": "iota", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "iotabtc"},
    {"base-currency": "poly", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "polybtc"},
    {"base-currency": "kan", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "kanbtc"},
    {"base-currency": "lba", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "lbabtc"},
    {"base-currency": "wan", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wanbtc"},
    {"base-currency": "bft", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bftbtc"},
    {"base-currency": "btm", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btmbtc"},
    {"base-currency": "ont", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ontbtc"},
    {"base-currency": "iost", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "iostbtc"},
    {"base-currency": "ht", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "htbtc"},
    {"base-currency": "trx", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "trxbtc"},
    {"base-currency": "smt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "smtbtc"},
    {"base-currency": "ela", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "elabtc"},
    {"base-currency": "wicc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wiccbtc"},
    {"base-currency": "ocn", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ocnbtc"},
    {"base-currency": "zla", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zlabtc"},
    {"base-currency": "abt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "abtbtc"},
    {"base-currency": "mtx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mtxbtc"},
    {"base-currency": "nas", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "nasbtc"},
    {"base-currency": "ven", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "venbtc"},
    {"base-currency": "dta", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dtabtc"},
    {"base-currency": "neo", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "neobtc"},
    {"base-currency": "wax", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "waxbtc"},
    {"base-currency": "bts", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btsbtc"},
    {"base-currency": "zil", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zilbtc"},
    {"base-currency": "theta", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "thetabtc"},
    {"base-currency": "ctxc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ctxcbtc"},
    {"base-currency": "srn", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "srnbtc"},
    {"base-currency": "xem", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xembtc"},
    {"base-currency": "icx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "icxbtc"},
    {"base-currency": "dgd", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "dgdbtc"},
    {"base-currency": "chat", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "chatbtc"},
    {"base-currency": "wpr", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wprbtc"},
    {"base-currency": "lun", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "lunbtc"},
    {"base-currency": "swftc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "swftcbtc"},
    {"base-currency": "snt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "sntbtc"},
    {"base-currency": "meet", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "meetbtc"},
    {"base-currency": "yee", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "yeebtc"},
    {"base-currency": "elf", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "elfbtc"},
    {"base-currency": "let", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "letbtc"},
    {"base-currency": "qtum", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "qtumbtc"},
    {"base-currency": "lsk", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "lskbtc"},
    {"base-currency": "itc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "itcbtc"},
    {"base-currency": "soc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "socbtc"},
    {"base-currency": "qash", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "qashbtc"},
    {"base-currency": "mds", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "mdsbtc"},
    {"base-currency": "eko", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ekobtc"},
    {"base-currency": "topc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "topcbtc"},
    {"base-currency": "mtn", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mtnbtc"},
    {"base-currency": "act", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "actbtc"},
    {"base-currency": "hc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "hcbtc"},
    {"base-currency": "stk", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "stkbtc"},
    {"base-currency": "storj", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "storjbtc"},
    {"base-currency": "gnx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "gnxbtc"},
    {"base-currency": "dbc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dbcbtc"},
    {"base-currency": "snc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "sncbtc"},
    {"base-currency": "cmt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cmtbtc"},
    {"base-currency": "tnb", "quote-currency": "btc", "price-precision": 10, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "tnbbtc"},
    {"base-currency": "ruff", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ruffbtc"},
    {"base-currency": "qun", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "qunbtc"},
    {"base-currency": "zrx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zrxbtc"},
    {"base-currency": "knc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "kncbtc"},
    {"base-currency": "blz", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "blzbtc"},
    {"base-currency": "propy", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "propybtc"},
    {"base-currency": "phx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "phxbtc"},
    {"base-currency": "appc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "appcbtc"},
    {"base-currency": "aidoc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "aidocbtc"},
    {"base-currency": "powr", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "powrbtc"},
    {"base-currency": "cvc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "cvcbtc"},
    {"base-currency": "pay", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "paybtc"},
    {"base-currency": "qsp", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "qspbtc"},
    {"base-currency": "dat", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "datbtc"},
    {"base-currency": "rdn", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "rdnbtc"},
    {"base-currency": "mco", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "mcobtc"},
    {"base-currency": "rcn", "quote-currency": "btc", "price-precision": 10, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "rcnbtc"},
    {"base-currency": "mana", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "manabtc"},
    {"base-currency": "utk", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "utkbtc"},
    {"base-currency": "tnt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "tntbtc"},
    {"base-currency": "gas", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "gasbtc"},
    {"base-currency": "bat", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "batbtc"},
    {"base-currency": "ost", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ostbtc"},
    {"base-currency": "link", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "linkbtc"},
    {"base-currency": "gnt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gntbtc"},
    {"base-currency": "mtl", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "mtlbtc"},
    {"base-currency": "evx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "evxbtc"},
    {"base-currency": "req", "quote-currency": "btc", "price-precision": 8, "amount-precision": 1,
     "symbol-partition": "innovation", "symbol": "reqbtc"},
    {"base-currency": "adx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "adxbtc"},
    {"base-currency": "ast", "quote-currency": "btc", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "astbtc"},
    {"base-currency": "eng", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "engbtc"},
    {"base-currency": "salt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "saltbtc"},
    {"base-currency": "edu", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "edubtc"},
    {"base-currency": "xvg", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xvgbtc"},
    {"base-currency": "wtc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wtcbtc"},
    {"base-currency": "bifi", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "bifibtc"},
    {"base-currency": "bcx", "quote-currency": "btc", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "bcxbtc"},
    {"base-currency": "bcd", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "bcdbtc"},
    {"base-currency": "sbtc", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "sbtcbtc"},
    {"base-currency": "btg", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "btgbtc"},
    {"base-currency": "xmr", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "xmreth"},
    {"base-currency": "eos", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "eoseth"},
    {"base-currency": "omg", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "omgeth"},
    {"base-currency": "iota", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "iotaeth"},
    {"base-currency": "ada", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "adaeth"},
    {"base-currency": "steem", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "steemeth"},
    {"base-currency": "poly", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "polyeth"},
    {"base-currency": "kan", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "kaneth"},
    {"base-currency": "lba", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "lbaeth"},
    {"base-currency": "wan", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "waneth"},
    {"base-currency": "bft", "quote-currency": "eth", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "bfteth"},
    {"base-currency": "zrx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zrxeth"},
    {"base-currency": "ast", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "asteth"},
    {"base-currency": "knc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "knceth"},
    {"base-currency": "ont", "quote-currency": "eth", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "onteth"},
    {"base-currency": "ht", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "hteth"},
    {"base-currency": "btm", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btmeth"},
    {"base-currency": "iost", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "iosteth"},
    {"base-currency": "smt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "smteth"},
    {"base-currency": "ela", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "elaeth"},
    {"base-currency": "trx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "trxeth"},
    {"base-currency": "abt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "abteth"},
    {"base-currency": "nas", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "naseth"},
    {"base-currency": "ocn", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ocneth"},
    {"base-currency": "wicc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wicceth"},
    {"base-currency": "zil", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zileth"},
    {"base-currency": "ctxc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ctxceth"},
    {"base-currency": "zla", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zlaeth"},
    {"base-currency": "wpr", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "wpreth"},
    {"base-currency": "dta", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dtaeth"},
    {"base-currency": "mtx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mtxeth"},
    {"base-currency": "theta", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "thetaeth"},
    {"base-currency": "srn", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "srneth"},
    {"base-currency": "ven", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "veneth"},
    {"base-currency": "bts", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "btseth"},
    {"base-currency": "wax", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "waxeth"},
    {"base-currency": "hc", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "hceth"},
    {"base-currency": "icx", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "icxeth"},
    {"base-currency": "mtn", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mtneth"},
    {"base-currency": "act", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "acteth"},
    {"base-currency": "blz", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "blzeth"},
    {"base-currency": "qash", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "qasheth"},
    {"base-currency": "ruff", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ruffeth"},
    {"base-currency": "cmt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cmteth"},
    {"base-currency": "elf", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "elfeth"},
    {"base-currency": "meet", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "meeteth"},
    {"base-currency": "soc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "soceth"},
    {"base-currency": "qtum", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "qtumeth"},
    {"base-currency": "itc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "itceth"},
    {"base-currency": "swftc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "swftceth"},
    {"base-currency": "yee", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "yeeeth"},
    {"base-currency": "lsk", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "lsketh"},
    {"base-currency": "lun", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "luneth"},
    {"base-currency": "let", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "leteth"},
    {"base-currency": "gnx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "gnxeth"},
    {"base-currency": "chat", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "chateth"},
    {"base-currency": "eko", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ekoeth"},
    {"base-currency": "topc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "topceth"},
    {"base-currency": "dgd", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "dgdeth"},
    {"base-currency": "stk", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "stketh"},
    {"base-currency": "mds", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "mdseth"},
    {"base-currency": "dbc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dbceth"},
    {"base-currency": "snc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "snceth"},
    {"base-currency": "pay", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "payeth"},
    {"base-currency": "qun", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "quneth"},
    {"base-currency": "aidoc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "aidoceth"},
    {"base-currency": "tnb", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "tnbeth"},
    {"base-currency": "appc", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "appceth"},
    {"base-currency": "rdn", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "rdneth"},
    {"base-currency": "utk", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "utketh"},
    {"base-currency": "powr", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "powreth"},
    {"base-currency": "bat", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "bateth"},
    {"base-currency": "propy", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "propyeth"},
    {"base-currency": "mana", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "manaeth"},
    {"base-currency": "req", "quote-currency": "eth", "price-precision": 8, "amount-precision": 1,
     "symbol-partition": "innovation", "symbol": "reqeth"},
    {"base-currency": "cvc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "cvceth"},
    {"base-currency": "qsp", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "qspeth"},
    {"base-currency": "evx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "evxeth"},
    {"base-currency": "dat", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dateth"},
    {"base-currency": "mco", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "mcoeth"},
    {"base-currency": "gnt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gnteth"},
    {"base-currency": "gas", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "gaseth"},
    {"base-currency": "ost", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "osteth"},
    {"base-currency": "link", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "linketh"},
    {"base-currency": "rcn", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "rcneth"},
    {"base-currency": "tnt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 0,
     "symbol-partition": "innovation", "symbol": "tnteth"},
    {"base-currency": "eng", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "engeth"},
    {"base-currency": "salt", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "salteth"},
    {"base-currency": "adx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "adxeth"},
    {"base-currency": "edu", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "edueth"},
    {"base-currency": "xvg", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xvgeth"},
    {"base-currency": "wtc", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "wtceth"},
    {"base-currency": "xrp", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "xrpht"},
    {"base-currency": "iost", "quote-currency": "ht", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "iostht"},
    {"base-currency": "dash", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "dashht"},
    {"base-currency": "wicc", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "wiccusdt"},
    {"base-currency": "eos", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "eosht"},
    {"base-currency": "bch", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "bchht"},
    {"base-currency": "ltc", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ltcht"},
    {"base-currency": "etc", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "etcht"},
    {"base-currency": "waves", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "wavesbtc"},
    {"base-currency": "waves", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "waveseth"},
    {"base-currency": "hb10", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "hb10usdt"},
    {"base-currency": "cmt", "quote-currency": "usdt", "price-precision": 4, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "cmtusdt"},
    {"base-currency": "dcr", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "dcrbtc"},
    {"base-currency": "dcr", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "dcreth"},
    {"base-currency": "pai", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "paibtc"},
    {"base-currency": "pai", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "paieth"},
    {"base-currency": "box", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "boxbtc"},
    {"base-currency": "box", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "boxeth"},
    {"base-currency": "dgb", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dgbbtc"},
    {"base-currency": "dgb", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dgbeth"},
    {"base-currency": "gxs", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gxsbtc"},
    {"base-currency": "gxs", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "gxseth"},
    {"base-currency": "xlm", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xlmbtc"},
    {"base-currency": "xlm", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "xlmeth"},
    {"base-currency": "bix", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bixbtc"},
    {"base-currency": "bix", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "bixeth"},
    {"base-currency": "bix", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "bixusdt"},
    {"base-currency": "hit", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "hitbtc"},
    {"base-currency": "hit", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "hiteth"},
    {"base-currency": "pai", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "paiusdt"},
    {"base-currency": "bt1", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "bt1btc"},
    {"base-currency": "bt2", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "bifurcation", "symbol": "bt2btc"},
    {"base-currency": "xzc", "quote-currency": "btc", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "xzcbtc"},
    {"base-currency": "xzc", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "xzceth"},
    {"base-currency": "vet", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "vetusdt"},
    {"base-currency": "vet", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "veteth"},
    {"base-currency": "vet", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "vetbtc"},
    {"base-currency": "ncash", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ncasheth"},
    {"base-currency": "ncash", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ncashbtc"},
    {"base-currency": "grs", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "grsbtc"},
    {"base-currency": "grs", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "grseth"},
    {"base-currency": "rccc", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "rccceth"},
    {"base-currency": "egcc", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "egcceth"},
    {"base-currency": "iic", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "iiceth"},
    {"base-currency": "she", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "sheeth"},
    {"base-currency": "rccc", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "rcccbtc"},
    {"base-currency": "mex", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mexeth"},
    {"base-currency": "ekt", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "ekteth"},
    {"base-currency": "bkbt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bkbteth"},
    {"base-currency": "gtc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gtceth"},
    {"base-currency": "hot", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "hoteth"},
    {"base-currency": "fti", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ftieth"},
    {"base-currency": "gsc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gsceth"},
    {"base-currency": "pc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "pceth"},
    {"base-currency": "xmx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xmxeth"},
    {"base-currency": "lym", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "lymeth"},
    {"base-currency": "cnn", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cnneth"},
    {"base-currency": "man", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "maneth"},
    {"base-currency": "uc", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "uceth"},
    {"base-currency": "aac", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "aaceth"},
    {"base-currency": "fair", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "faireth"},
    {"base-currency": "seele", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "seeleeth"},
    {"base-currency": "uip", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "uipeth"},
    {"base-currency": "lxt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "lxteth"},
    {"base-currency": "datx", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "datxeth"},
    {"base-currency": "get", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "geteth"},
    {"base-currency": "ae", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "aeeth"},
    {"base-currency": "uuu", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "uuueth"},
    {"base-currency": "ycc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ycceth"},
    {"base-currency": "cdc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cdceth"},
    {"base-currency": "but", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "buteth"},
    {"base-currency": "portal", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "portaleth"},
    {"base-currency": "ssp", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "sspeth"},
    {"base-currency": "ren", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "reneth"},
    {"base-currency": "mt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mteth"},
    {"base-currency": "rte", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "rtebtc"},
    {"base-currency": "fti", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ftibtc"},
    {"base-currency": "ekt", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ektbtc"},
    {"base-currency": "ren", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "renbtc"},
    {"base-currency": "zjlt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zjlteth"},
    {"base-currency": "tos", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "tosbtc"},
    {"base-currency": "get", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "getbtc"},
    {"base-currency": "ssp", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "sspbtc"},
    {"base-currency": "musk", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "muskbtc"},
    {"base-currency": "cnn", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cnnbtc"},
    {"base-currency": "tos", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "toseth"},
    {"base-currency": "gve", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gveeth"},
    {"base-currency": "ae", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "aebtc"},
    {"base-currency": "ncc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "nccbtc"},
    {"base-currency": "kcash", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "kcasheth"},
    {"base-currency": "ycc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "yccbtc"},
    {"base-currency": "18c", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "18ceth"},
    {"base-currency": "pnt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "pnteth"},
    {"base-currency": "cvcoin", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "cvcoineth"},
    {"base-currency": "ncc", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ncceth"},
    {"base-currency": "bcv", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bcvbtc"},
    {"base-currency": "uip", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "uipbtc"},
    {"base-currency": "pnt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "pntbtc"},
    {"base-currency": "dac", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "daceth"},
    {"base-currency": "trio", "quote-currency": "eth", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "trioeth"},
    {"base-currency": "seele", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "seelebtc"},
    {"base-currency": "hot", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "hotbtc"},
    {"base-currency": "bcv", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bcveth"},
    {"base-currency": "musk", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "musketh"},
    {"base-currency": "gtc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gtcbtc"},
    {"base-currency": "bkbt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "bkbtbtc"},
    {"base-currency": "man", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "manbtc"},
    {"base-currency": "aac", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "aacbtc"},
    {"base-currency": "uc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "ucbtc"},
    {"base-currency": "she", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "shebtc"},
    {"base-currency": "but", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "butbtc"},
    {"base-currency": "idt", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "idteth"},
    {"base-currency": "mex", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mexbtc"},
    {"base-currency": "idt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "idtbtc"},
    {"base-currency": "datx", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "datxbtc"},
    {"base-currency": "zjlt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "zjltbtc"},
    {"base-currency": "fair", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "fairbtc"},
    {"base-currency": "iic", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "iicbtc"},
    {"base-currency": "rte", "quote-currency": "eth", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "rteeth"},
    {"base-currency": "cdc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cdcbtc"},
    {"base-currency": "pc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "pcbtc"},
    {"base-currency": "dac", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "dacbtc"},
    {"base-currency": "egcc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "egccbtc"},
    {"base-currency": "xmx", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "xmxbtc"},
    {"base-currency": "gsc", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gscbtc"},
    {"base-currency": "lxt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "lxtbtc"},
    {"base-currency": "portal", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "portalbtc"},
    {"base-currency": "lym", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "lymbtc"},
    {"base-currency": "uuu", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "uuubtc"},
    {"base-currency": "trio", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "triobtc"},
    {"base-currency": "kcash", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "kcashbtc"},
    {"base-currency": "mt", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "mtht"},
    {"base-currency": "mt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "mtbtc"},
    {"base-currency": "kcash", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "kcashht"},
    {"base-currency": "18c", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "18cbtc"},
    {"base-currency": "gve", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "gvebtc"},
    {"base-currency": "cvcoin", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "cvcoinbtc"},
    {"base-currency": "ardr", "quote-currency": "btc", "price-precision": 8, "amount-precision": 2,
     "symbol-partition": "main", "symbol": "ardrbtc"},
    {"base-currency": "ardr", "quote-currency": "eth", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "main", "symbol": "ardreth"},
    {"base-currency": "hpt", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "hptusdt"},
    {"base-currency": "hpt", "quote-currency": "btc", "price-precision": 10, "amount-precision": 2,
     "symbol-partition": "innovation", "symbol": "hptbtc"},
    {"base-currency": "hpt", "quote-currency": "ht", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "hptht"},
    {"base-currency": "xlm", "quote-currency": "usdt", "price-precision": 6, "amount-precision": 4,
     "symbol-partition": "innovation", "symbol": "xlmusdt"}]}
import requests, json
url = "https://api.huobi.pro/v1/common/symbols"



response = requests.get(url=url)
data = json.loads(response.text)


def getPrecision(data, symbol):
    for item in data["data"]:
        if item["symbol"] == symbol.lower().replace("_", ""):
            return item["amount-precision"]


print(getPrecision(data,"ETC_BTC"))
